#--------------------------------------------------|--------------------------------------------------#
                                      # AWSTemplateFormatVersion
#--------------------------------------------------|--------------------------------------------------#

AWSTemplateFormatVersion: '2010-09-09'

#--------------------------------------------------|--------------------------------------------------#
                                            # Description:
#--------------------------------------------------|--------------------------------------------------#

Description: S3

#--------------------------------------------------|--------------------------------------------------#
                                              # Metadata
#--------------------------------------------------|--------------------------------------------------#

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Select the project name
        Parameters:
          - ProjectName


#--------------------------------------------------|--------------------------------------------------#
                                            # Parameters
#--------------------------------------------------|--------------------------------------------------#

Parameters:
  ProjectName:
    Type: String
    Default: lecture10
    Description: Select the stack name you want to add

#--------------------------------------------------|--------------------------------------------------#
                                            # Resources
#--------------------------------------------------|--------------------------------------------------#

Resources:

#--------------------------------------------------|--------------------------------------------------#
# SecurityGroup

  EC2toS3:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: 
        Fn::ImportValue: !Sub ${ProjectName}-ID-VPC
      GroupName: 'OutS3@EC2'
      GroupDescription: Allow access to Amazon S3
      SecurityGroupIngress: []
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          DestinationPrefixListId: pl-61a54008
      Tags:
      - Key: Name
        Value: !Sub "[${ProjectName}]OutS3@EC2"

# SecurityGroup end
#--------------------------------------------------|--------------------------------------------------#

#--------------------------------------------------|--------------------------------------------------#
# S3

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${ProjectName}.images
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-S3-Bucket"

# S3 end
#--------------------------------------------------|--------------------------------------------------#


#--------------------------------------------------|--------------------------------------------------#
                                              # Out put
#--------------------------------------------------|--------------------------------------------------#

Outputs:

#--------------------------------------------------|--------------------------------------------------#
# SecurityGroup

  EC2toS3Id:
    Value: !Ref EC2toS3
    Export:
      Name: !Sub ${ProjectName}-ID-SG-EC2toS3

# SecurityGroup end
#--------------------------------------------------|--------------------------------------------------#

#--------------------------------------------------|--------------------------------------------------#
# S3

  # S3Bucket:

# S3 end
#--------------------------------------------------|--------------------------------------------------#
